app/views/richer-claimant-info.html
app/views/richer-claimant-info/v10/change-singular/behaviour.html
app/views/richer-claimant-info/v10/pip-claimant-detail-updated-behaviour.html
package-lock.json

Updated Keep Customer Interactions Safe screen and added extra radio button for "not known"
Updated success banner on referral details page.

Update KCIS with not known radio

---

app/views/richer-claimant-info/v10/pip-claimant-detail-updated-behaviour.html
app/views/richer-claimant-info/v10/pip-claimant-detail-updated.html
app/views/richer-claimant-info/v10/pip-claimant-detail.html

Field moved to personal details

Move safety measures field to correct location

---

app/views/richer-claimant-info.html
app/views/richer-claimant-info/v9/sc3-medical-evidence/timeline.html
app/views/richer-claimant-info/v9/sc4-assessment-booked/pip-claimant-detail-updated.html

Scenario 3 timeline updated to reflect PIP case
Scenario 4 success banner content updated
Richer claimant info page amended to reflect scenario updates

Content updated for UR

---

app/views/richer-claimant-info/v9/sc3-medical-evidence/timeline.html

Timeline content and right hand menu amended to reflect a PIP claim at the 'awaiting medical evidence' status

Timeline amended

---

app/views/richer-claimant-info/v9/sc3-medical-evidence/timeline.html

Add new entry relating to  medical evidence

Timeline updated

---

app/views/richer-claimant-info/v9/sc1-questionnaire/interrupt-page.html

Changed from question to instruction.

Updated warning content

---

app/routes.js
app/views/richer-claimant-info/v11/change-singular/consent-gp.html
app/views/richer-claimant-info/v11/change-singular/important-behaviour.html
app/views/richer-claimant-info/v11/change-singular/important-end-of-life.html
app/views/richer-claimant-info/v11/change-singular/important-support.html
app/views/richer-claimant-info/v11/pip-case-details-updated-as.html
app/views/richer-claimant-info/v11/pip-case-details-updated-consent.html
app/views/richer-claimant-info/v11/pip-case-details-updated-endoflife.html
app/views/richer-claimant-info/v11/pip-case-details.html
app/views/richer-claimant-info/v11/pip-claimant-detail-updated-behaviour.html
app/views/richer-claimant-info/v11/pip-claimant-detail-updated-interpreter.html
app/views/richer-claimant-info/v11/pip-claimant-detail.html
app/views/richer-claimant-info/v8/change-singular/consent-gp.html

Fixed pages where fields were displaying default text instead of entered data

Fixed pages where fields were displaying default text

---

app/views/richer-claimant-info/v11/pip-claimant-detail-wide.html

Fixed id for Contact details so subnav anchor will work

Fixed id for H1 Contact details

---

app/routes.js
app/views/richer-claimant-info/v11/change-singular/wca/behaviour.html
app/views/richer-claimant-info/v11/change-singular/wca/consent-gp.html
app/views/richer-claimant-info/v11/change-singular/wca/important-end-of-life.html
app/views/richer-claimant-info/v11/change-singular/wca/important-support.html
app/views/richer-claimant-info/v11/change-singular/wca/interpreter-remove.html
app/views/richer-claimant-info/v11/change-singular/wca/interpreter.html
app/views/richer-claimant-info/v11/change-singular/wca/mental-health.html
app/views/richer-claimant-info/v11/change-singular/wca/personal-home-no.html
app/views/richer-claimant-info/v11/change-singular/wca/personal-home-remove.html
app/views/richer-claimant-info/v11/change-singular/wca/personal-mob-no.html
app/views/richer-claimant-info/v11/change-singular/wca/personal-mobile-remove.html
app/views/richer-claimant-info/v11/wca-case-details-updated-consent.html
app/views/richer-claimant-info/v11/wca-case-details-updated-endoflife.html
app/views/richer-claimant-info/v11/wca-case-details-updated-mh.html
app/views/richer-claimant-info/v11/wca-case-details.html
app/views/richer-claimant-info/v11/wca-claimant-detail-updated-behaviour.html
app/views/richer-claimant-info/v11/wca-claimant-detail-updated-interpreter-removed.html
app/views/richer-claimant-info/v11/wca-claimant-detail-updated-interpreter.html
app/views/richer-claimant-info/v11/wca-claimant-detail.html

New referral and claimant details. New WCA change and remove pages

Create WCA specific referral details page

---

app/views/richer-claimant-info.html

Update main menu

---

app/routes.js
app/views/richer-claimant-info/v11/pip-case-details-updated-as.html
app/views/richer-claimant-info/v11/pip-case-details-updated-behaviour.html
app/views/richer-claimant-info/v11/pip-case-details-updated-consent.html
app/views/richer-claimant-info/v11/pip-case-details-updated-endoflife.html
app/views/richer-claimant-info/v11/pip-case-details.html
app/views/richer-claimant-info/v11/pip-claimant-detail.html
app/views/richer-claimant-info/v11/wca-case-details-updated-consent.html
app/views/richer-claimant-info/v11/wca-case-details.html

Update success banner with 'referral details'
Add new h1

Move 'safety measures' to referral

---

app/views/richer-claimant-info/v7-1/pip-case-details-updated.html
app/views/richer-claimant-info/v7-1/pip-case-details.html
app/views/richer-claimant-info/v7-1/pip-claimant-detail-updated.html
app/views/richer-claimant-info/v7-1/pip-claimant-detail.html

- Updated 'Case overview' to 'Referral overview'
- Updated 'Case details' to 'Referral details'
- Removed chevrons in lefthand nav

Updated lefthand nav to reflect live and latest decisions

---

app/views/richer-claimant-info/v7-1/pip-case-details-updated.html
app/views/richer-claimant-info/v7-1/pip-case-details.html

- Updated H2 from 'Case details' to 'Referral details' to match the lefthand nav

Updated H2 on referral details page

---

app/views/richer-claimant-info/v7-1/change-singular/medical-find-address-confirm.html
app/views/richer-claimant-info/v7-1/change-singular/medical-find-address-select.html

Updated the XX postcodes to reflect a more realistic HTA area postcode

Updated postcode in change specialist details

---

app/views/richer-claimant-info/v12/pip-case-details.html
app/views/richer-claimant-info/v12/pip-claimant-detail-updated-as.html
app/views/richer-claimant-info/v12/pip-claimant-detail-updated.html
app/views/richer-claimant-info/v12/pip-claimant-detail.html

- Updated v12 of prototype side nav terminology from 'Referral details' to 'Referral overview', so it is all consistent with PIP new service updates

Updated v12 of prototype side nav

---

app/views/richer-claimant-info/v7-1/change-singular/correspondence-find-address-confirm.html
app/views/richer-claimant-info/v7-1/change-singular/correspondence-find-address-select.html
app/views/richer-claimant-info/v7-1/change-singular/correspondence-find-address.html
app/views/richer-claimant-info/v7-1/change-singular/personal-find-address-confirm.html
app/views/richer-claimant-info/v7-1/change-singular/personal-find-address-select.html
app/views/richer-claimant-info/v7-1/change-singular/personal-find-address.html
app/views/richer-claimant-info/v7-1/change-singular/representation-address-confirm.html
app/views/richer-claimant-info/v7-1/change-singular/representation-address-lookup.html

- Updated placeholder 'XX' postcodes in v7.1 for residential, correspondence and appointee address change

Updated placeholder 'XX' postcodes

---

app/views/index.njk
app/views/pip-has-integration/pip-has-integration.html

- New intro text for the PIP HAS integration card on the index page
- New intro text on the PIP HAS integration landing page

New intro text for PIP HAS integration

---

app/views/pip-has-integration/v1/pip-case-details.html

- Updated fields to display those that are relevant for PIP thin slice, as per Jira ticket and Mural board

Updated pip case details page in v1 prototype

---

app/views/pip-has-integration/v1/pip-case-details-updated.html

- To reflect agreed fields in Jira task and Mural board

Updated 'pip-case-details-updated' page

---

app/views/pip-has-integration/pip-has-integration.html
app/views/richer-claimant-info.html

- For links in v12 of claimant data prototype
- For links in v1 of PIP HAS integration prototype

Added 'opens in new tab' text

---

app/views/pip-has-integration/v1/change-singular/important-behaviour.html
app/views/pip-has-integration/v1/change-singular/important-end-of-life.html
app/views/pip-has-integration/v1/change-singular/interpreter.html
app/views/pip-has-integration/v1/change-singular/personal-dod.html
app/views/pip-has-integration/v1/pip-case-details-updated.html
app/views/pip-has-integration/v1/pip-claimant-detail-updated.html

- Updated button text for pages that are editable to reflect the live environment (i.e change SREL, safety measures etc) -Enabled data parsing for editable information such as Safety measures and interpreter
- Update to content on the editable safety measure page to remove mentions of UCB

Updates to data parsing and button text

---

app/views/pip-has-integration/v1/pip-case-details-updated.html
app/views/pip-has-integration/v1/pip-case-details.html

For PIP HAS integration v1 - Added PIP Service referral ID field on referral details page.
Jira ticket: https://dwpdigital.atlassian.net/browse/HTC-2587

Added PIP Service referral ID field

---

app/views/pip-has-integration/v1/index.html
app/views/pip-has-integration/v1/view-caseload-or-status.html

PIP HAS integration prototype v1:
- Update to cards on main menu (index) page
- New view caseload or status page

Updates to main menu

---

app/views/pip-has-integration/v1/change-singular/interpreter-remove.html
app/views/pip-has-integration/v1/pip-claimant-detail-updated.html

Added new content to interpreter remove page

Renamed GP details remove page to Interpreter remove page

---

app/views/layout.html
package-lock.json
package.json

Conditional reveals for radios not working, so prototype kit help channel advised to make this update. It hasn't seemed to work, but decided as best practice we should update anyway as it might help new features in the future

Updates on layout.html template to v13 prototype kit

---

app/views/pip-has-integration/v1/change-singular/dod-remove.html
app/views/pip-has-integration/v1/change-singular/interpreter-remove.html
app/views/pip-has-integration/v1/pip-claimant-detail-updated-no-success-banner.html

This page has been created to link from the remove interpreter and remove date of death pages if user selects 'No' they do not wish to remove.

new page for pip claimant details updated but with no success banner

---

app/views/pip-has-integration/v1/pip-case-details-updated.html
app/views/pip-has-integration/v1/pip-case-details.html

- Removed 'GP details' from left hand sub nav
- updated 'Specialist contacts' in sub nav to 'Health or care professional contacts'

Updated lefthand sub nav in referral details area

---

app/views/pip-has-integration/v1/pip-case-details-updated.html
app/views/pip-has-integration/v1/pip-case-details.html

On referral details page, updated terminology from 'Health or care professional contacts' to 'Health or care professionals contact details'

Updated terminology for Health and care professionals

---

app/views/pip-has-integration/v1/pip-case-details-updated.html
app/views/pip-has-integration/v1/pip-case-details.html

Changed the first line of address from 'Hospital' to street to reflect how the data is collected in PIP and passed to HAS

Updated health or care professional address
